name: Publish Github Page
# master branch on push, auto run
on: 
  push:
    branches:
      - hexo
      
jobs:
  build: 
    runs-on: ubuntu-latest
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js
      uses: actions/setup-node@v4 # 建议升级到 v3 或 v4
      with:
        node-version: '20' # 【关键】这里一定要改成 20 (至少 18)
    
    - name: Setup Hexo Dependencies
      run: |
        npm install hexo-cli -g
        npm install
    
    - name: Setup Deploy Private Key
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: Ensure nojekyll marker
      run: echo "" > public/.nojekyll
    - name: Deploy
      run: |
        git config --global user.name 'ningbo6'
        git config --global user.email '365220121@qq.com'
        hexo clean
        hexo deploy
